dataDir: "" # 本地数据存储目录，默认为 `~/.lsx（自定义时请写完整路径，不要使用 ~，结尾不要有 /）
remoteBaseUrl: "https://unpkg.com/linux-command@latest" # 远程命令数据源地址，默认为 `https://unpkg.com/linux-command@latest`
useLess:  false # 默认不以less分页输出，可通过手动方式输出：lsx show ls | less（windows可能不起作用）
useShow: false # 是否启用 show 子命令，默认 false不启用。则可以直接使用命令lsx查询，eg：lsx ls
